title: "Time to Taste: Predicting Cooking Durations Using Recipe Attributes"
description: Estimating the preparation times of newly shared recipes on food.com based on model trained with current recipes.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one